### ISSUE TITLE
Requirements for show_all

### ISSUE THREAD

**Issue by RajaSrinivasan** [jrcarter/Ada_GUI#12]
I build show_all

when I try to run it I get a web page with the text 

No file "" found

what is it looking for?

I am on a MacBook Pro (apple silicon)

Regards, Srini

**Comment by jrcarter** [comment]
The Readme says

> The Test directory contains boot.html, boot.js, and jquery.min.js. These files must be available to every Ada-GUI program. It also contains favicon.ico, an icon of Ada.

These are what is missing. Note also that

> The audio file glass.ogg is used by Show_All.
