### ISSUE TITLE
Consider using gnatprep for the OS string

### ISSUE THREAD

**Issue by TamaMcGlinn** [jrcarter/Ada_GUI#3]
> Before compiling Ada_GUI, you have to specify the OS on which it will be used. Open ada_gui-gnoga-application.adb in an editor and search for "OS_ID". Change the constant OS in the next line to match your OS (anything other than Mac OSX or Windows should use Unix). You can then compile the library.

Since you are requiring GNAT anyway, you could use gnatprep. That would mean you can put '$OS_ID' instead of the current string, and specify a value on the commandline with `gprbuild [other options] -gnateD Unix`. You can also add defaults in the gpr project file, and I believe gprbuild can also find out the OS automatically and pass it along as the default. To support cross-compiling it should still be overridable.

When I have some time I could implement this; [these docs](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/the_gnat_compilation_model.html#preprocessing-with-gnatprep) helped me implement something similar a year ago.

**Comment by jrcarter** [comment]
There's a good reason the ARM doesn't provide a preprocessor, so you won't find me using one.

As stated in the Readme, gprbuild has a serious problem with unnecessary recompilation, so I'm not using it, either.
