### ISSUE TITLE
GCC 12 problem

### ISSUE THREAD

**Issue by simonjwright** [jrcarter/Ada_GUI#4]
Compiling with GCC 12.0.1 of 20220311 (probably quite close to the official 12.1.0), get
```
gnat-sockets-server.adb:320:25: error: object subtype must statically match designated subtype
```
where
```
   316.          Connect_Socket
   317.          (  Socket   => Client.Socket,
   318.             Server   => Client.Client_Address,
   319.             Timeout  => 0.0,
   320.             Selector => Listener.Selector'Unchecked_Access,
                                |
        >>> error: object subtype must statically match designated subtype

   321.             Status   => Status
   322.          );
```

I don’t know whether this is real or the compiler getting confused: I tried to build a reproducer but failed.
```
with GNAT.Sockets;
with Ada.Finalization;
procedure Socket_Problem is
   type Connection_Server is new Ada.Finalization.Limited_Controlled
      with record
         Selector : aliased GNAT.Sockets.Selector_Type;
      end record;
   Listener : Connection_Server;
   Dummy_Client_Socket : GNAT.Sockets.Socket_Type;
   Client_Address : GNAT.Sockets.Sock_Addr_Type;
   Status : GNAT.Sockets.Selector_Status;
begin
   GNAT.Sockets.Connect_Socket
     (Socket   => Dummy_Client_Socket,
      Server   => Client_Address,
      Timeout  => 0.0,
      Selector => Listener.Selector'Unchecked_Access,
      Status   => Status);
end Socket_Problem;
```
(I started off with a simple record, then limited, then limited_controlled: all OK)

**Comment by jrcarter** [comment]
Interesting. This is part of Kazakov's Simple Components, so you should probably report it there, too. It is also part of Gnoga, and I'm sure they would like to hear about it.

**Comment by jrcarter** [comment]
I note that the changes for the Simple Components v4.62 includes

> GNAT 12.1 bugs worked around in several package, in particular, in GNAT.Sockets.Server

I prefer not to change correct code to work around compiler errors, but rather to wait for a version of the compiler that corrects the errors.
