### ISSUE TITLE
Build and use on MacOS

### ISSUE THREAD

**Issue by RajaSrinivasan** [jrcarter/Ada_GUI#9]
I was hoping to try out Ada_GUI but am not able to build. I am getting the following error:

a. cloned the repo.
b. cd Test

gcc -c -gnatan -gnato2 -O2 -fstack-check -I=../ show_all.adb
show_all.adb:9:06: error: file "ada_gui.ads" not found
gnatmake: "show_all.adb" compilation error

help appreciated

**Comment by jrcarter** [comment]
I know that others have successfully used Ada GUI on Mac OS. I presume you have ascertained that ada_gui.ads is in the parent directory and is readable. I'm not sure what the problem could be. I suggest going to the main Ada-GUI directory, and trying

1. cp Test/show_all.adb .
2. gnatmake -gnatan -gnato2 -O2 -fstack-check show_all.adb
3. chmod -w ada_gui*.ali

If this succeeds, then try again from the Test directory.

**Comment by RajaSrinivasan** [comment]
Jeffrey

Thanks. Much progress. Now getting to the next step:

gcc -c -gnatan -gnato2 -O2 -fstack-check
gnat-sockets-connection_state_machine.adb

gnat-sockets-connection_state_machine.adb:808:17: warning: formal parameter
"Item" is read but never assigned [-gnatwf]

gcc -c -gnatan -gnato2 -O2 -fstack-check
gnat-sockets-connection_state_machine-http_server.adb

gnat-sockets-server.adb:320:25: error: object subtype must statically match
designated subtype

gnatmake: "gnat-sockets-connection_state_machine-http_server.adb"
compilation error

gnatmake --version

GNATMAKE 12.1.0

Copyright (C) 1995-2022, Free Software Foundation, Inc.

This is free software; see the source for copying conditions.

There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.


I am not familiar with these packages. Will dig in. If the solution is
obvious to you, I would appreciate it.


Regards, srini

**Comment by jrcarter** [comment]
The Simple Components have many warnings if compiled with warnings on. The README.md has a section titled "Compiler Errors", which says, "Note that GNAT 12[.1] has an error that prevents it from compiling GNAT.Sockets.Server." This appears to be what you're encountering. I recommend staying with GNAT 11. Alternatively, the most recent version of the Simple Components has a work-around for the compiler error. You can replace all the Simple Component source files (those supplied in the main directory that do not start with "ada_gui") with a standard version of the Simple Components if you like, as described in the README.

**Comment by jrcarter** [comment]
Closing as solved due to inactivity.
